import {
  NUS,
  GPT,
  Freelancer,
  earthbrain,
  eyewa,
  maqro,
  fountain,
  ringo,
  trp,
} from "../assets/images";
import {
  DynamoDB,
  GCP,
  SendGrid,
  adonis,
  antdesign,
  aws,
  bootstrap,
  car,
  contact,
  css,
  django,
  docker,
  elastic,
  estate,
  express,
  firestore,
  git,
  github,
  gitlab,
  golang,
  heroku,
  html,
  javascript,
  jest,
  jquery,
  linkedin,
  mongodb,
  mui,
  mysql,
  nest,
  netlify,
  nextjs,
  nodejs,
  postgresql,
  pricewise,
  python,
  quasar,
  react,
  redis,
  redux,
  sass,
  snapgram,
  socket,
  stripe,
  summiz,
  tailwindcss,
  threads,
  twilio,
  typescript,
  vercel,
  vue,
  vuex,
} from "../assets/icons";

export const SKILL_TYPE = {
  FRONTEND: "Frontend",
  BACKEND: "Backend",
  DATABASE: "Database",
  SERVICE: "Service",
  VERSION_CONTROL: "Version Control",
  DEVOPS: "Devops",
  STATE_MANAGEMENT: "State Management",
  OTHER: "Other",
};

export const skills = [
  {
    imageUrl: nextjs,
    name: "Next.js",
    yoe: 2,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: nodejs,
    name: "Node.js",
    yoe: 4,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: react,
    name: "React",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: redux,
    name: "Redux",
    yoe: 3,
    type: "State Management",
    order: 1,
  },
  {
    imageUrl: vuex,
    name: "VueX",
    yoe: 3,
    type: "State Management",
    order: 1,
  },
  {
    imageUrl: sass,
    name: "Sass",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: typescript,
    name: "TypeScript",
    yoe: 3,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: css,
    name: "CSS",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: javascript,
    name: "JavaScript",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: html,
    name: "HTML",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: express,
    name: "Express",
    yoe: 2,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: git,
    name: "Git",
    yoe: 4,
    type: "Version Control",
    order: 1,
  },
  {
    imageUrl: github,
    name: "GitHub",
    yoe: 4,
    type: "Version Control",
    order: 1,
  },
  {
    imageUrl: mongodb,
    name: "MongoDB",
    yoe: 1,
    type: "Database",
    order: 1,
  },
  {
    imageUrl: mui,
    name: "Material-UI",
    yoe: 3,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: adonis,
    name: "AdonisJS",
    yoe: 1,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: antdesign,
    name: "Ant Design",
    yoe: 1,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: aws,
    name: "AWS",
    yoe: 2,
    type: "Devops",
    order: 1,
  },
  {
    imageUrl: GCP,
    name: "Google Cloud",
    yoe: 2,
    type: "Devops",
    order: 1,
  },
  {
    imageUrl: bootstrap,
    name: "Bootstrap",
    yoe: 4,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: django,
    name: "Django",
    yoe: 0.5,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: docker,
    name: "Docker",
    yoe: 2,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: DynamoDB,
    name: "DynamoDB",
    yoe: 0.5,
    type: "Database",
    order: 1,
  },
  {
    imageUrl: elastic,
    name: "Elastic",
    yoe: 1,
    type: "Service",
    order: 1,
  },
  {
    imageUrl: firestore,
    name: "Firebase",
    yoe: 2,
    type: "Database",
    order: 1,
  },
  {
    imageUrl: gitlab,
    name: "Gitlab",
    yoe: 2,
    type: "Version Control",
    order: 1,
  },
  {
    imageUrl: golang,
    name: "Go",
    yoe: 2,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: heroku,
    name: "Heroku",
    yoe: 2,
    type: "Devops",
    order: 1,
  },
  {
    imageUrl: jest,
    name: "Jest",
    yoe: 2,
    type: "Test",
    order: 1,
  },
  {
    imageUrl: jquery,
    name: "Jquery",
    yoe: 1,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: mysql,
    name: "MySQL",
    yoe: 4,
    type: "Database",
    order: 1,
  },
  {
    imageUrl: nest,
    name: "NestJS",
    yoe: 2,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: netlify,
    name: "Netlify",
    yoe: 2,
    type: "Devops",
    order: 1,
  },
  {
    imageUrl: postgresql,
    name: "PostgreSQL",
    yoe: 3,
    type: "Database",
    order: 1,
  },
  {
    imageUrl: python,
    name: "Python",
    yoe: 1,
    type: "Backend",
    order: 1,
  },
  {
    imageUrl: quasar,
    name: "Quasar",
    yoe: 1,
    type: "Frontend",
    order: 1,
  },
  {
    imageUrl: redis,
    name: "Redis",
    yoe: 3,
    type: "Database",
    order: 1,
  },
  {
    imageUrl: SendGrid,
    name: "SendGrid",
    yoe: 1,
    type: "Service",
    order: 1,
  },
  {
    imageUrl: socket,
    name: "Socket",
    yoe: 2,
    type: "Service",
    order: 1,
  },
  {
    imageUrl: stripe,
    name: "Stripe",
    yoe: 2,
    type: "Service",
    order: 1,
  },
  {
    imageUrl: twilio,
    name: "Twilio",
    yoe: 1,
    type: "Service",
    order: 1,
  },
  {
    imageUrl: vercel,
    name: "Vercel",
    yoe: 2,
    type: "Devops",
    order: 1,
  },
  {
    imageUrl: vue,
    name: "Vue.js",
    yoe: 2,
    type: "Frontend",
    order: 1,
  },
];

export const experiences = [
  {
    title: "Full Stack Developer",
    company_name: "NUS Technology • HCMC",
    company_link: "https://nustechnology.com/",
    icon: NUS,
    iconBg: "#accbe1",
    date: "December 2021 - Present",
    points: [
      "Diverse Project Experience: Contributed to over 10 projects across various industries, including E-commerce, Travel, Construction, Education, Stock, CMS, Security, and Logistics",
      "CI/CD System Construction: Established a CI/CD system on GitHub, streamlining code quality analysis and saving significant development time by assisting teammates in code quality evaluation and improvement strategies",
      "Payment System Integration: Implemented the Stripe payment mechanism within applications, facilitating easier user payments and managing complex payment cycles through direct client consultations.",
      "Interface and Performance Strategy: Developed a strategy that enhanced the user interface and doubled the access speed by delivering rapid and high-quality images.",
      `Multi-Stage Delivery Pipeline: Configured a multi-stage Delivery Pipeline in GKE that
            automated the workflow from code commit to deployment, incorporating custom build steps,
            integrating unit and integration tests, and ensuring artifact storage in Container Registry.`,
      `Multilingual Application Development: Built applications in Golang and NodeJS on an open platform, enabling simultaneous site construction in two languages. Also developed custom Oauth2 authentication using Golang and Authlete.`,
    ],
  },
  {
    title: "Full Stack Developer",
    company_name: "GPT Group",
    company_link: "https://www.gptgroup.net/",
    icon: GPT,
    iconBg: "#fbc3bc",
    date: "Jan 2021 - November 2021",
    points: [
      "Project Contribution: Played a pivotal role in over 2 major projects, focusing on enhancing code quality and providing crucial code reviews for team members.",
      "Sprint Planning and Management: Determined sprint goals and task lists for each sprint, collaborating with team members to accurately estimate the time and resources needed for each task",
      "Project Ownership and Quality Assurance: Took full ownership of projects, ensuring the codebase was of the highest quality and managing technical debts effectively",
      "Architectural Leadership: Provided critical architectural and design direction, assessed risks, and evaluated the impact of new features and implementations on the system’s integrity.",
      "Code Refactoring and Efficiency: Led efforts in refactoring and creating reusable components, resulting in a significant  reduction of over 200 development hours monthly",
    ],
  },
  {
    title: "Frontend Developer",
    company_name: "Freelancer",
    company_link: "#",
    icon: Freelancer,
    iconBg: "#b7e4c7",
    date: "2019 - December 2020",
    points: [
      "Adaptive Responsive Design: Implemented advanced responsive design techniques, enabling optimal application use across diverse devices.",
      "JWT Authentication and Authorization: Integrated JWT for robust authentication and authorization processes.",
      "Continuous Learning and Tech Upgrades: Embracing a growth mindset, frontend developers continually seek out new technologies, tools, and methodologies to stay updated with the rapidly evolving landscape of web development. This proactive approach involves engaging in online courses, attending workshops, reading industry blogs, and participating in developer communities to expand knowledge and skill sets.",
      "Championing Single-Page Application Development: Architected a sophisticated single-page application leveraging React, Redux, and TypeScript, fostering efficient navigation and resource utilization within the organizational ecosystem.",
      "Problem-Solving and Research: Frontend developers excel in problem-solving by meticulously researching and analyzing various solutions to address complex technical challenges. They leverage resources such as documentation, forums, and peer collaboration to explore alternative approaches, troubleshoot issues, and implement robust solutions that meet project requirements effectively. This dedication to thorough problem-solving ensures the delivery of high-quality and innovative frontend solutions.",
    ],
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "/contact",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/hoainho",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/hoai-nho/",
  },
];

export const projects = [
  {
    iconUrl: earthbrain,
    theme: "btn-back-blue",
    name: "Earthbrain - Smart Construction",
    description:
      "My primary responsibilities encompassed a comprehensive focus on accountability, issue resolution, support provision, and adept time management. I dedicated myself to ensuring the highest standards of responsibility in every task undertaken, guaranteeing that all aspects of the project were executed with precision and diligence. My role was pivotal in identifying and resolving complex issues promptly, thereby maintaining project momentum and ensuring seamless progression. I provided unwavering support to both my team and stakeholders, facilitating a collaborative and productive working environment. Moreover, my effective time management skills were crucial in optimizing project workflows, meeting deadlines, and achieving project objectives efficiently",
    link: "https://www.earthbrain.com/",
  },
  {
    iconUrl: eyewa,
    theme: "btn-back-green",
    name: "Eyewa",
    description:
      "I played a pivotal role in developing a comprehensive e-commerce application specializing in eyewear products catering to the international market. The platform was designed to facilitate seamless transactions across multiple countries, including UAE, Saudi Arabia, Kuwait, Qatar, Oman, and Bahrain. Leveraging the React framework, I led the frontend development efforts, ensuring an intuitive and responsive user interface that catered to the diverse needs of our global customer base",
    link: "https://eyewa.com/",
  },
  {
    iconUrl: fountain,
    theme: "btn-back-red",
    name: "Fountain Gifts",
    description:
      "I have developed an application service catering to e-commerce needs, utilizing Next.js 14 and custom hooks to incorporate multiple intricate features. Emphasis has been placed on optimizing UI performance to ensure smooth and user-friendly interactions. Furthermore, I have enhanced the system with meticulous attention to perfect pixel implementation, thereby enhancing the overall customer experience to the highest standard.",
    link: "https://www.fountaingifts.com/",
  },
  {
    iconUrl: ringo,
    theme: "btn-back-pink",
    name: "Ringo App",
    description: `My primary focus revolved around refining the administrative tools essential for overseeing worker activities effectively. Although my direct involvement didn't extend to crafting the landing page, my contributions played a vital role in ensuring a fluid and intuitive user experience within the administrative interface.`,
    link: "https://ringoapp.com.au/",
  },
  {
    iconUrl: maqro,
    theme: "btn-back-black",
    name: "Maqro",
    description: `I spearheaded a pivotal project aimed at revolutionizing the stock market landscape for investors. At its core, this project entailed the development of a dynamic server tailored specifically for mobile platforms. Leveraging my expertise in frameworks such as AdonisJS, along with implementing cutting-edge technologies like Socket.io and Bull for background job management and queueing, I engineered a robust and scalable infrastructure to meet the demands of real-time stock data processing. Utilizing AWS for seamless deployment, I orchestrated the creation of a responsive and intuitive UI, complete with dynamic, real-time charting capabilities. Furthermore, I engineered intricate functionalities including payment processing, stock trading, and data optimization, enabling smooth interactions through APIs even with large datasets. This project not only showcased my technical prociency but also my ability to innovate and deliver solutions that elevate user experiences in the financial domain.`,
    link: "https://maqro.com.au/",
  },
  {
    iconUrl: trp,
    theme: "btn-back-yellow",
    name: "ThirdRockPix",
    description:
      "I took on a multifaceted role, embracing accountability, issue resolution, support provision, and efficient time management as my primary responsibilities. At the heart of this platform lies a revolutionary file upload feature, empowering travelers to share their experiences in stunning detail with files of up to 50GB per upload. From breathtaking landscapes to unforgettable moments, no memory is too grand to be captured and shared.",
    link: "https://thirdrockpix.com/",
  },
];
